name: slim_conservation_orthogroup_generation
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - pip
  - pandas
  - numpy
  - jupyter
  - biopython>=1.8
  - cd-hit
  - ca-certificates
  - certifi
  - openssl
  - mafft
  - python-dotenv
  - pyprojroot
  - tabulate
  - pip:
    - alfpy
