overwrite: true

filter_params:
  min_fraction_shorter_than_query: 0.5

og_select_params:
  OG_selection_method: level_name
  OG_level_name: Vertebrata

ldo_select_params:
  LDO_selection_method: alfpy_google_distance
  # LDO_selection_method: msa
  # LDO_selection_method: msa_by_organism
  # LDO_selection_method: pairwise

align_params:
  align: false
  n_align_threads: 8

main_output_folder: output
